before_install: gem install bundler
language: node_js
node_js:
- node
script:
- 
deploy:
  provider: firebase
  token:
    secure: E2Lmf1oVbaB1SZDZNopGZr6l3KWcET6wz/6gWhIGQMwHlx706RA/XK2RpoTMD9infbrIhu9HfiUlvpqhGB8tabWb0YqBi56wMUvqm61ep3CVbNK7BA+UHCVZP5Hm84AajVchmKWY1RM2HGbSkvFrkCRp1ZCUhphAEl42WyaQmY2hYGJ60DI9hrCEKH2HC1Nt5GzMaUQLF3roLSMk8Jgwe3Kt7w5VMb3boP54BsbcfY7iF+aU+cKlQMyMsLts2oQFmY7bfe8AYO2zM7ZswA0lathygYti+dT2cRRNE8fvSt0X+48SN7x5hr/AZi6fxrfI+G2c7HtsDYN7zSAC+qclVNnGNaZpUMsbugWL4hPdsH8FGHHPI6GcKmtbdnH6daPaAOQCJednx9gP0T+UpSSefC9KiN8yccgkQW5eW/3iakGcUz/uIQ+VqUTwJwi4OE1CjxX+Km24RcD34BSKpYqUnRozc5xY1lTNxa0jsqVCj7H8b8uwYRf0xrE7mfo3d+g2Xrh/gvQNIDcS6dayqBOkx0E1lEdGguvphv/Kx9vlB5ts3Io76AMAT0e+nAhmPf0m0p9/Vk1wkIMoBJdym4DekMY2MXe1CXh+079+E2PODFFBhY4Q2uV0YfNOaipfMU41IbXa2uyNvZBT3ZVc+fmmiPyR2sGBBYEAWzO50+crOls=
  message: deploying to website
  project: kayla-s-first-website