language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: kaiDVr6ndea4VmKwMEdcKSBSCzgPGoc26h5GqlIOXseXITxkhxWJbvMU5sasvuEHKnKY6HLp5EpJgruGuOkb/WLbFvQZ46Uu4lZS8kjWe6wMBIDgtMUbchNww3cx9fGOe7ekILPcemIeGIp04+W9ZtYeUETKvgNvXiHGxTSDrjxR3/bm3oZYKGit+6fJm5LcXd6LJffJYo2aMUBetpYYqeCBbR8IiltIwTFTq61vb40PNm8jM7Wy20N/9gvU0C0caX04J7D4G6oBegfi/+f6kgqL3SrG1Gm8YDTmnCYepRTon4OK88jhG+hR5WatCRWYoqKJr+rVRqM3mJFwV8I/nom2eebi/bEfS7vMIJ19G28kzmJuS9uYe3OMYgcjlcltu+jiP/uQ7Ac5A3Uiit0Ekg/UqBj1OstvjDd4u4Na9QSrvN7IDqOTuiOYjX31UzB/xLGsUx8lu/HjK+Iv50P4GJ4ej7L8I8sKQZSZlMzrRSgMdTpAx43FUrw47arLcnmnxwu4n2zNbgVK6xRnVZqaYdemgODR7VQw+fTq0qnhtMGnCXnCh7D+t9CGIf7H1tAU0jJYAR9GJhqkhDI1ycfd0XB8bnthLD/RyKnI2wfW4BsxLJaBegDBnhLO+xYp9dNyvtMPeNtrXl/BhTR/Xx4WCnG4dQ/xWVqI2/k+CzWny64=
  message: deploying to website